apiVersion: v1
kind: Service
metadata:
  name: quarkusapp
  labels:
    app: quarkus
spec:
  selector:
    app: quarkus
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkusapp
  labels:
    app: quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus
  template:
    metadata:
      labels:
        app: quarkus
    spec:
      containers:
      - name: quarkus
        image: ndigrazia/quarkus-demo:1.0.0
        env:
        - name: GREETING_MESSAGE
          value: "Hallo"
        - name: GREETING_SUFFIX
          value: "!!!!!!"  
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-quarkus-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  ingressClassName: public
  rules:
  - host: quarkus-local-microk8s.local.com
    http:
      paths:
      - path: "/quarkus/(.*)"
        pathType: Prefix
        backend:
          service:
            name: quarkusapp 
            port:
              number: 8080
